### ISSUE TITLE
Idea: Add implememtation (references)?

### ISSUE THREAD

**Issue by baentsch** [ietf-wg-pquip/state-of-protocols-and-pqc#4]
Thanks for this great collection of specs and their state. Very good one-stop place.

Looking at the charta of this WG, "...document associated operational guidance with respect to PQC...", would it be an idea to add here also references to projects implementing those specs? And/or what about links to projects doing interop testing for those specs? Or should that be located somewhere (where?) else?

**Comment by claucece** [comment]
That is very interesting @baentsch ! I agree! If you want to send a PR about it, go ahead! I'll try to work a bit on this next week.

**Comment by paulehoffman** [comment]
The start of the list is in #7
